### ISSUE TITLE
Error after opening LimitPriceChoice function and reloading settings

### ISSUE THREAD

**Issue by TeQTabanca** [EpiCanard/GlobalMarketChest#125]
Issue goal: **Bug**
Platform: **Spigot 1.13.2-R0.1-SNAPSHOT**
Plugin version: **1.10.1**

**Description**

After turning on the LimitPriceChoice function, the error occurs when I reload the settings, **but when I restart the server, such an error does not occur.**

**Screenshots**

![hata-1](https://user-images.githubusercontent.com/89253304/130228870-fbb53351-557f-49af-9f16-3227e80af171.png)
![hata-2](https://user-images.githubusercontent.com/89253304/130228898-0ac199f8-5bc7-4f02-9bad-6d04fe4f88ee.png)

**Comment by EpiCanard** [comment]
I will investigate this evenning.
Strange bug.

**Comment by EpiCanard** [comment]
I didn't succeed to reproduce the bug.
I tried with spigot 1.13.2 and GMC 1.10.1 with reload of plugin and reload of server and all works has expected.

Are you sure you didn't change the content of `price-limits.yml` with invalid yaml ?

**Comment by EpiCanard** [comment]
`-` is for list. Here we are not inside a list but in an object.
Remove all the `-` before the name of the item.

**Comment by TeQTabanca** [comment]
------------------------------------------------------------------------------------------------------------------------------------------
> I didn't succeed to reproduce the bug.
> I tried with spigot 1.13.2 and GMC 1.10.1 with reload of plugin and reload of server and all works has expected.
> 
> Are you sure you didn't change the content of `price-limits.yml` with invalid yaml ?
------------------------------------------------------------------------------------------------------------------------------------------

**Did you set this function to 'true' when testing it on the test server?**


**Because when i open this function i get error.**

![Price Limit](https://user-images.githubusercontent.com/89253304/131213477-93ab8477-fd11-4e48-b4f1-5fb4d746d6d8.png)

**NOT**:
When i try on my test server i get the same error again and only vault,economy and globalmarketchest are installed...

------------------------------------------------------------------------------------------------------------------------------------------
> `-` is for list. Here we are not inside a list but in an object.
> Remove all the `-` before the name of the item.

**I don't understand what you are saying. My English is not very good so I translate from the internet. Could you please explain with a picture? Sure, if you have time.**

**Comment by EpiCanard** [comment]
Your price-limits look like this
```yaml
- minecraft:dirt:
  Min: 10
  Max: 1000
- minecraft:stone:
  Min: 20.0
  Max: -1.0
```

But it should look like this
 ```yaml
minecraft:dirt:
  Min: 10
  Max: 1000
minecraft:stone:
  Min: 20.0
  Max: -1.0
```

You must remove the character `-` before the word `minecraft`

**Comment by TeQTabanca** [comment]
**I think you misunderstood. before the word minecraft `-` it has no character!**

`-` **there is**

![tireli](https://user-images.githubusercontent.com/89253304/131215632-d1c73388-e6b1-4a3f-a083-3e32f59ec1f3.png)


`-` **none**

![tiresiz](https://user-images.githubusercontent.com/89253304/131215633-2d8599fd-bd2d-4c5c-a6e8-2b01a8ce6d5f.png)

Example:

Before the word minecraft - i added the character and this error occured.

```
[12:59:32 WARN]: Unexpected exception while parsing console command "globalmarketchest reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'globalmarketchest' in plugin GlobalMarketChest v1.10.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689) [server.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [server.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [server.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block collection
 in 'reader', line 19, column 1:
     - minecraft:cod_bucket:
    ^
expected <block end>, but found '?'
 in 'reader', line 22, column 1:
     minecraft:iron_leggings:
    ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:516) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:188) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:142) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at fr.epicanard.duckconfig.parsers.yaml.YamlParser.load(YamlParser.java:23) ~[?:?]
        at fr.epicanard.duckconfig.parsers.yaml.YamlParser.loadMap(YamlParser.java:33) ~[?:?]
        at fr.epicanard.duckconfig.DuckLoader.lambda$loadMap$0(DuckLoader.java:76) ~[?:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at fr.epicanard.duckconfig.DuckLoader.loadMap(DuckLoader.java:76) ~[?:?]
        at fr.epicanard.globalmarketchest.configuration.ConfigLoader.loadPriceLimitConfig(ConfigLoader.java:150) ~[?:?]
        at fr.epicanard.globalmarketchest.GlobalMarketChest.onEnable(GlobalMarketChest.java:110) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        at fr.epicanard.globalmarketchest.GlobalMarketChest.reload(GlobalMarketChest.java:158) ~[?:?]
        at fr.epicanard.globalmarketchest.commands.consumers.ReloadConsumer.accept(ReloadConsumer.java:26) ~[?:?]
        at fr.epicanard.globalmarketchest.commands.CommandNode.execute(CommandNode.java:188) ~[?:?]
        at fr.epicanard.globalmarketchest.commands.CommandNode.execute(CommandNode.java:192) ~[?:?]
        at fr.epicanard.globalmarketchest.commands.CommandHandler.onCommand(CommandHandler.java:100) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-1a3504a-84f3da3]
        ... 8 more
```

**in 'reader', line 19, column 1:
     - minecraft:cod_bucket:
    ^
expected <block end>, but found '?'
 in 'reader', line 22, column 1:
     minecraft:iron_leggings:
    ^**

**Comment by EpiCanard** [comment]
Can you send me your file price-limits.yml ? It will be easier for me to try to reproduce the bug and find it with your file.

**Comment by TeQTabanca** [comment]
[price-limits.zip](https://github.com/EpiCanard/GlobalMarketChest/files/7070611/price-limits.zip)

**Comment by EpiCanard** [comment]
Ok found it.
YAML files use indentation.


Instead of using YAML generator use a simple text editor and add 2 spaces before each `Min` and `Max`

**Comment by TeQTabanca** [comment]
Could you please give an example?

**Comment by EpiCanard** [comment]
I removed my answer because I was a bug with my text editor. I still try to find where come from your bug

**Comment by EpiCanard** [comment]
To be honest I don't know.

I know where it comes from but not why it doesn't work.

I will not be available for the end of the weelend.

**Comment by EpiCanard** [comment]
Can you try this version ?  https://jenkins.epicanard.com/job/GlobalMarketChest-dev-builds/85/

**Comment by EpiCanard** [comment]
Thank you :)
