### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by RanWhite** [EpiCanard/GlobalMarketChest#126]
[02:02:23] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[02:02:23] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[02:02:23] [Server thread/WARN]: 	at fr.epicanard.globalmarketchest.utils.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:35)
[02:02:23] [Server thread/WARN]: 	at fr.epicanard.globalmarketchest.utils.reflection.VersionSupportUtils.hasNbtTag(VersionSupportUtils.java:358)
[02:02:23] [Server thread/WARN]: 	at fr.epicanard.globalmarketchest.utils.PlayerUtils.removeDuplicateItems(PlayerUtils.java:229)
[02:02:23] [Server thread/WARN]: 	at fr.epicanard.globalmarketchest.listeners.CloseGUICollector.onInventoryCloseEvent(CloseGUICollector.java:41)
[02:02:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:02:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[02:02:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:02:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1347)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.q(EntityPlayer.java:1450)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:440)
[02:02:23] [Server thread/WARN]: 	at me.filoghost.chestcommands.inventory.DefaultMenuView.close(DefaultMenuView.java:49)
[02:02:23] [Server thread/WARN]: 	at me.filoghost.chestcommands.icon.InternalConfigurableIcon.onClick(InternalConfigurableIcon.java:121)
[02:02:23] [Server thread/WARN]: 	at me.filoghost.chestcommands.listener.InventoryListener.lambda$onLateInventoryClick$0(InventoryListener.java:84)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1205)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1033)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[02:02:23] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[02:02:23] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[02:02:23] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[02:02:23] [Server thread/WARN]: 	at fr.epicanard.globalmarketchest.utils.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:35)
[02:02:23] [Server thread/WARN]: 	at fr.epicanard.globalmarketchest.utils.reflection.VersionSupportUtils.hasNbtTag(VersionSupportUtils.java:358)
[02:02:23] [Server thread/WARN]: 	at fr.epicanard.globalmarketchest.utils.PlayerUtils.removeDuplicateItems(PlayerUtils.java:229)
[02:02:23] [Server thread/WARN]: 	at fr.epicanard.globalmarketchest.listeners.CloseGUICollector.onInventoryCloseEvent(CloseGUICollector.java:41)
[02:02:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:02:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[02:02:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:02:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1347)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.q(EntityPlayer.java:1450)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:440)
[02:02:23] [Server thread/WARN]: 	at me.filoghost.chestcommands.inventory.DefaultMenuView.close(DefaultMenuView.java:49)
[02:02:23] [Server thread/WARN]: 	at me.filoghost.chestcommands.icon.InternalConfigurableIcon.onClick(InternalConfigurableIcon.java:121)
[02:02:23] [Server thread/WARN]: 	at me.filoghost.chestcommands.listener.InventoryListener.lambda$onLateInventoryClick$0(InventoryListener.java:84)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82)
[02:02:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1205)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1033)
[02:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[02:02:23] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[02:02:23] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()

**Comment by EpiCanard** [comment]
I was waiting spigot to start adding the support 1.18. now it's out I will start to work on it.

**Comment by RanWhite** [comment]
> I was waiting spigot to start adding the support 1.18. now it's out I will start to work on it.

Thank you for your hard work!
