### ISSUE TITLE
duplicating items

### ISSUE THREAD

**Issue by Unix-User** [EpiCanard/GlobalMarketChest#139]
Issue Goal : Bug

Platform: purpur-1.20.2-2095

Plugin version : 1.15

Description : 
duplicating items when using mysql, to reproduce the behavior, a player must add a lot of itens on the shop then cancel the transaction, sometimes the item is not removed from the shop and it can be withdrawn 2 or more times

**Comment by EpiCanard** [comment]
I will try to reproduce but at first it could be an issue with purpur

**Comment by Unix-User** [comment]
yes, not error, but a warn. take a look:

```
[11:18:26] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND `playerStarter` = '120c9848-b992-3a7d-8b76-e8e143d8561b' AND `group` = 'Pe' at line 1
[11:18:26] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[11:18:26] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[11:18:26] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[11:18:26] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
[11:18:26] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
[11:18:26] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
[11:18:26] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
[11:18:26] [Server thread/WARN]: 	at GlobalMarketChest-1.15.0.jar//fr.epicanard.globalmarketchest.database.querybuilder.builders.UpdateBuilder.execute(UpdateBuilder.java:56)
[11:18:26] [Server thread/WARN]: 	at GlobalMarketChest-1.15.0.jar//fr.epicanard.globalmarketchest.database.querybuilder.QueryExecutor.execute(QueryExecutor.java:87)
[11:18:26] [Server thread/WARN]: 	at GlobalMarketChest-1.15.0.jar//fr.epicanard.globalmarketchest.database.querybuilder.QueryExecutor.execute(QueryExecutor.java:116)
[11:18:26] [Server thread/WARN]: 	at GlobalMarketChest-1.15.0.jar//fr.epicanard.globalmarketchest.managers.AuctionManager.undoGroupOfPlayerAuctions(AuctionManager.java:162)
[11:18:26] [Server thread/WARN]: 	at GlobalMarketChest-1.15.0.jar//fr.epicanard.globalmarketchest.gui.shops.interfaces.AuctionGlobalView.undoEveryAuction(AuctionGlobalView.java:124)
[11:18:26] [Server thread/WARN]: 	at GlobalMarketChest-1.15.0.jar//fr.epicanard.globalmarketchest.gui.shops.baseinterfaces.ShopInterface.lambda$onClick$7(ShopInterface.java:121)
[11:18:26] [Server thread/WARN]: 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[11:18:26] [Server thread/WARN]: 	at GlobalMarketChest-1.15.0.jar//fr.epicanard.globalmarketchest.gui.shops.baseinterfaces.ShopInterface.onClick(ShopInterface.java:121)
[11:18:26] [Server thread/WARN]: 	at GlobalMarketChest-1.15.0.jar//fr.epicanard.globalmarketchest.listeners.GUIListener.onClick(GUIListener.java:48)
[11:18:26] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor546.execute(Unknown Source)
[11:18:26] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[11:18:26] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[11:18:26] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:18:26] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:18:26] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[11:18:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3183)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1351)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1328)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1321)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1299)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1187)
[11:18:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[11:18:26] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
´´´

but looks like this is not related to the duplication event, i checked all transactions and some don't throw any warn.

**Comment by EpiCanard** [comment]
I think that is the cause of duplicate because the exception is when you undo a group of auctions. Which version of MySQL do you have ?

**Comment by Unix-User** [comment]
i'm using mysql 8. but, as i said before, sometimes the server wont throw any exception, even the duplications still happen

**Comment by EpiCanard** [comment]
I didn't succeed to reproduce the bug.

I tried to fix the issue with sql error that comes (I think) when you try to undo a group of auctions without any space available in your inventory.

Can you try this version and tell me if it works ?
[GlobalMarketChest-1.15.1.zip](https://github.com/EpiCanard/GlobalMarketChest/files/13929797/GlobalMarketChest-1.15.1.zip)

**Comment by EpiCanard** [comment]
At least this error is fixed.

But for the duplication issue I don't know. To be clear, the process to reproduce is :
- Create multiple auctions with 1 item (more than 1 page so more than 27 auctions ?)
- Undo a group of auctions <-- there you have a duplication 
When I try this it give me my 27 items or less if I don't have enough place.

On your message above I see that you reload, create an auction and delete the shop.
Is it the duplication you are talking about ?
When you delete a shop, the auctions are not deleted, they are still there and if you create a new shop with the same name you will find them has before.

**Comment by Unix-User** [comment]
to reproduce just create 1 auction(no need to be multiple auctions), then just click multiple times on the cancel auction button, dont wait the process to be complete just keep clicking and you will see the the item duplicating. i think there is a delay betwen the remove of mysql record and the minecraft retrieve item, so when i receive the item on my inventory the record still on mysql then i can cancel the auction again, and again, and agaim so on.

**Comment by EpiCanard** [comment]
What your describe really feel like a big latency between you, your server and your database.
I can try to add security when you undo a group of auctions.
In most cases the database responds quickly and you don't have the time to duplicate the item.

**Comment by Unix-User** [comment]
yeah i know, but i made tests with the server and database are on the same machine with the same results.

**Comment by EpiCanard** [comment]
I added some security check. It can't fix your latency issue but it should prevent to be able to cancel an auction already canceled and fix the duplication issue.

Tell me if it's good for you.
[GlobalMarketChest-1.15.1-bis.zip](https://github.com/EpiCanard/GlobalMarketChest/files/13999004/GlobalMarketChest-1.15.1-bis.zip)

**Comment by Unix-User** [comment]
i've made a short test and looks like the problem is solved

**Comment by EpiCanard** [comment]
Fix released https://www.spigotmc.org/resources/globalmarketchest-gui-shop-plugin.64921/update?update=531253
