### ISSUE TITLE
Support 1.20.6

### ISSUE THREAD

**Issue by MSCMDD** [EpiCanard/GlobalMarketChest#142]
[16:57:06 ERROR]: Error occurred while enabling GlobalMarketChest v1.15.1 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at GlobalMarketChest-1.15.1.jar/fr.epicanard.globalmarketchest.utils.reflection.VersionSupportUtils.<init>(VersionSupportUtils.java:47) ~[GlobalMarketChest-1.15.1.jar:?]
        at GlobalMarketChest-1.15.1.jar/fr.epicanard.globalmarketchest.utils.reflection.VersionSupportUtils.getInstance(VersionSupportUtils.java:55) ~[GlobalMarketChest-1.15.1.jar:?]
        at GlobalMarketChest-1.15.1.jar/fr.epicanard.globalmarketchest.utils.ItemStackUtils.getItemStack(ItemStackUtils.java:46) ~[GlobalMarketChest-1.15.1.jar:?]
        at GlobalMarketChest-1.15.1.jar/fr.epicanard.globalmarketchest.utils.ShopUtils.lambda$init$1(ShopUtils.java:62) ~[GlobalMarketChest-1.15.1.jar:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at GlobalMarketChest-1.15.1.jar/fr.epicanard.globalmarketchest.utils.ShopUtils.init(ShopUtils.java:61) ~[GlobalMarketChest-1.15.1.jar:?]
        at GlobalMarketChest-1.15.1.jar/fr.epicanard.globalmarketchest.GlobalMarketChest.onEnable(GlobalMarketChest.java:83) ~[GlobalMarketChest-1.15.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaves-1.20.6.jar:1.20.6-213-6951bdc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaves-1.20.6.jar:1.20.6-213-6951bdc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:608) ~[leaves-1.20.6.jar:1.20.6-213-6951bdc]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:557) ~[leaves-1.20.6.jar:1.20.6-213-6951bdc]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[leaves-1.20.6.jar:1.20.6-213-6951bdc]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[leaves-1.20.6.jar:1.20.6-213-6951bdc]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[leaves-1.20.6.jar:1.20.6-213-6951bdc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1135) ~[leaves-1.20.6.jar:1.20.6-213-6951bdc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[leaves-1.20.6.jar:1.20.6-213-6951bdc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:57:07 INFO]: [GlobalMarketChest] Disabling GlobalMarketChest v1.15.1

**Comment by EpiCanard** [comment]
The fix is not easy but I'm already on it

**Comment by EpiCanard** [comment]
Minecraft 1.20.6 is now supported in GMC 1.15.2
